# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pr: 
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '45e3c083-bfeb-4f9f-bd31-4cb3efd92e57'
  imageRepository: 'konmaripoweb'
  containerRegistry: 'konmaripocontainerregistry.azurecr.io'
  buildContextLocation: '$(Build.SourcesDirectory)/src/Konmaripo.Web'
  dockerfilePath: '$(Build.SourcesDirectory)/src/Konmaripo.Web/Konmaripo.Web/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: "$(buildContextLocation)"
        tags: |
          $(tag)
          konmaripoweb
    - task: Docker@2
      displayName: Push an image to container registry
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        command: push
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          konmaripoweb
